baseURL = "https://ImBadAtNaming.github.io/"
languageCode = "en-us"
title = "ImBadAtNaming's Website"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "ImBadAtNaming"

[params]
author = "ImBadAtNaming"
description = "The website of ImBadAtNaming."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
mathjax = false

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

# Giscus support
GiscusRepo = ""  # mandatory
GiscusRepoId = ""  # mandatory
GiscusCategory = "Announcements" # mandatory
GiscusCategoryId = ""  # mandatory
GiscusLazyLoad = false  # optional

[[params.social]]
id = "docs"
url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/ImBadAtNaming/"

[menu]

[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about"
weight = 1

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true